// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcrdhSYh8C8otsyt7M_yHBR1o11eF7hZk',
    appId: '1:703328381763:web:79a72dc7f79ca2da6c5df6',
    messagingSenderId: '703328381763',
    projectId: 'app-medicine-24',
    authDomain: 'app-medicine-24.firebaseapp.com',
    storageBucket: 'app-medicine-24.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtxzrMTg2DdeiO8LOE5VO4fjYZYnGm7Us',
    appId: '1:703328381763:android:056a02db1906b0226c5df6',
    messagingSenderId: '703328381763',
    projectId: 'app-medicine-24',
    storageBucket: 'app-medicine-24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RLsfhmcuFp8A7hEcoiJrhJdFeXJftds',
    appId: '1:703328381763:ios:a96e9aa379f5bed86c5df6',
    messagingSenderId: '703328381763',
    projectId: 'app-medicine-24',
    storageBucket: 'app-medicine-24.appspot.com',
    iosBundleId: 'com.example.appMedicine',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RLsfhmcuFp8A7hEcoiJrhJdFeXJftds',
    appId: '1:703328381763:ios:7770a0f4324fe1416c5df6',
    messagingSenderId: '703328381763',
    projectId: 'app-medicine-24',
    storageBucket: 'app-medicine-24.appspot.com',
    iosBundleId: 'com.example.appMedicine.RunnerTests',
  );
}
